move storage location, and make customizable
This changes the location in which Grist files are stored. Tested
under a small test harness docker image rather than on ec2 itself,
so apologies in advance if I missed something.

It is a bit silly since in order to pick up the custom location,
I needed to hardcode the installation path into more scripts.
Feels like there could be a cleaner way to do all this.

Includes a few fixes to small typos.

diff --git a/cleanup b/cleanup
--- a/cleanup
+++ b/cleanup
@@ -1,7 +1,26 @@
+#!/bin/bash
+
+installation_path="/home/ubuntu/grist"
+
+# Check if gristParameters file exists and is readable
+if [ ! -r $installation_path/gristParameters ]; then
+  echo "Error: gristParameters file does not exist or is not readable."
+  exit 1
+fi
+
+# Read variables from gristParameters file
+source $installation_path/gristParameters
+
+# Check if STORAGE is set. If not, throw error
+if [ -z "$STORAGE" ]; then
+  echo "STORAGE environment variable not set."
+  exit 1
+fi
+
 # stop and remove all runing containers
 sudo docker stop $(sudo docker ps -a -q)
-#clean grist temp data 
-sudo rm -rf /tmp/grist-test
+#clean grist data
+sudo rm -rf $STORAGE
 #disable root login
 sudo passwd -l root
 # shred ssh keys
