Clean dex and grist databases when restartGrist script is called with "clean" flag

diff --git a/restartGrist b/restartGrist
--- a/restartGrist
+++ b/restartGrist
@@ -2,10 +2,19 @@
 #!/bin/bash
 
 # Check if the script received the cleanDex flag
-if [ "$1" = "cleanDex" ]; then
+if [ "$1" = "clean" ]; then
     # If so, delete the dex database
-    echo "Cleaning dex database..."
+    echo "Cleaning database..."
     rm -rf /tmp/grist-test/auth
+    if [ $? -ne 0 ]; then
+        echo "Failed to clean dex database."
+        exit 1
+    fi
+    rm -rf /tmp/grist-test/home.sqlite3
+    if [ $? -ne 0 ]; then
+        echo "Failed to clean grist database."
+        exit 1
+    fi
 fi
 
 # Restart the container
